version: '3'
services:
  app:
    build: .
    ports:
      - "3000:3000"   # Frontend
      - "5000:5000"   # Backend
    environment:
<<<<<<< HEAD
      - REACT_APP_BACKEND_URL=http://72.145.9.233:5000
=======
      - REACT_APP_BACKEND_URL=http://localhost:5000
>>>>>>> 82e6ba34d077ad6512d297adb8612f380b576110
      - SERVER_PORT=5000
      - NODE_ENV=production
    volumes:
      - /app/node_modules